### ISSUE TITLE
Changes to make (post-course)

### ISSUE THREAD

**Issue by ChasNelson1990** [ChasNelson1990/python-zero-to-hero-course#11]
- [x] Alter schedule timing to allow more time in the morning
- [x] Clarify: morning - learning basics, afternoon - demonstrating usefulness
- [ ] Make slides notebook less text heavy, i.e. remove objectives and key points
- [ ] Make sure slides are 16:9 compatible

**Comment by mixmixmix** [comment]
- [x] 1. Add more little exercises so that the methods are getting more reinforced. So for instance after introducing `for` loop: a) Three exercises: change the range of a for loop printing numbers (exercise, for changing stop, start and step) b) write a for loop printing numbers (this time from scratch). c) write a for loop adding numbers, etc.
- [x] 2. It seems people sometimes got stuck a bit, and others completed exercises much quicker. With such "reinforcement" exercises, we can give very little time and then go through them on the main screen so, everyone can see the solutions, possibly finish at home. We keep them engaged but also keep the pace. 
- [ ] 3. I think the text in the notebooks might be set in two different fonts. Main one, and a bit smaller italics with additional information to read at home. It would allow a bit more flexibility on the day as well, unlike just deleting excess
- [x] 4. Add information/talking point on how to switch types of cells and how to recognise what is the  type of cell. Also explain execution number and what "*" means. I think we can speed things up a bit by making people more aware of that.
- [ ] 5. Add more links, like [duck.com](duck.com), and links to plots gallery of matplotlib and seaborn
- [ ] 6. We can add an exercise where they copy in a plot from matplotlib gallery and make it work with Iris data. It can be something really complex and would introduce, _my improper way_ of producing graphs ;)

**Comment by ChasNelson1990** [comment]
@mixmixmix, what do you think of the new schedule (ods only).

**Comment by ChasNelson1990** [comment]
- [ ] Update 'Time' for each notebook once new schedule is agreed

**Comment by ChasNelson1990** [comment]
For reference:
* Tasks: `<div style="background-color:#abd9e9; border-radius: 5px; padding: 10pt"><strong>Task:</strong> A task.</div>`
* Exercies: `<div style="background-color:#fdae61; border-radius: 5px; padding: 10pt"><strong>Exercise:</strong> An exercise.</div>`

**Comment by ChasNelson1990** [comment]
@mixmixmix Can I get you to go through and add more links to things you think are important?

**Comment by ChasNelson1990** [comment]
- [ ] add a separate time for completing exercises

**Comment by ChasNelson1990** [comment]
So I've added some obvious extra tasks (which I've called exercises) to notebooks 01--08, i.e. the morning where we go through things more slowly.
It would be great if you, @mixmixmix, could:
1. Check these over and make sure you're happy with them
2. Add any extras you think would be useful

**Comment by ChasNelson1990** [comment]
(I'll go through the remaining notebooks tomorrow.)

**Comment by ChasNelson1990** [comment]
I've realised that, given we're splitting the day into 'interactive teaching' and 'showcasing modules' notebook 9 needs to be part of the core, taught slowly part. Have updated schedule and into in notebook 01 to reflect this.

**Comment by ChasNelson1990** [comment]
Think the key things here are done. Maybe still need to add a few more links or images?

**Comment by mixmixmix** [comment]
We can add this to modules intro ;)

![Image of Python](https://imgs.xkcd.com/comics/python.png )
